version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: app
    restart: always
    ports:
      - "${PORT}:3333"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - database
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    networks:
      - database
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    networks:
      - database

networks:
  database:
    name: database
    driver: bridge